Arjunkalidas/fpe-nodejs

- FF-1/common-utils/CommonUtils.js
updating the common utils with necessary utility functions like power, concatenate, bigInt calculations, xor, mod, int to bigInt conversions, and string to bigInt conversions
Adding appropriate validations for the parameters in the utility functions
> updating the common utils with necessary utility functions to be used in FF1 and Cipher

- FF-1/CharMap.js
- FF-1/Ciphers.js
- FF-1/CryptoUtil.js
- FF-1/FF1.js
* adding the core encrypt and decrypt logic in FF1 as per the NIST standard documentation in FF1 mode, 
* updating the crypto util alphanumeric and numeric char maps, 
* updating the references for CharMap and Ciphers to pick up the functions in the respective classes by creating a class instance in the consuming files
* cleaning up dummy references, unused variables and fixing typos in the error messages
> Core FPE FF1 mode logic, Cipher and CharMap updates

- FF-1/Ciphers.js
- FF-1/FPEncryption.js
- FF-1/common-utils/CommonUtils.js
- FF-1/common-utils/Constants.js
- package.json
- updating the todo items, renaming the files to match the mission, 
- updating package json and import statements in other classes
> Action items update plus clean up of imports & non-standard references

- .gitignore
- FF-1/Ciphers.js
- FF-1/CryptoUtil.js
- FF-1/common-utils/CommonUtils.js
- README.md
- index.js
- updating the code with comments wherever required, 
- updating the todo items, 
- cleaning up the gitignore file and 
- updating readme
> Code cleanup, commenting and readme

- README.md
- The readme was updated with "how to use" the library section, and added the code to perform the same.
- The usage code mentions import statement, creating cryptoUtil instance, invoking encrypt and decrypt methods
> Update README.md - usage code

- README.md
updating the code block in readme file
> Update README.md - code block update

- README.md
cleaning up code block in the instructions to make it more readable.
> Update README.md - cleanup of code block

- package.json
- adding attributes to make it more detailed and informative
- cleaned up unnecessary text, irrelevant attributes and made the description shorter
> Update package.json - cleaning up and adding attributes

- FF-1/Ciphers.js
- FF-1/CryptoUtil.js
- FF-1/FF1.js
- FF-1/FPEncryption.js
- FF-1/common-utils/CommonUtils.js
- FF-1/common-utils/Constants.js
- index.js
- package.json
FPEncryption changes and implementing byteArray, radixedIntArray in commonUtils.
and fixed few errors observed in numbyte and modBigInt logic. Fixed Wrapper call in CryptoUtil.
> FPEncryption changes and added byteArray logic

- README.md
- updating the NIST white paper links
- editing text
- updating the license information
> Update README.md  - updating the links & license info

- README.md
Editing the text alignment in the readme to trim text
> Editing the text alignment in the readme

- README.md
- Updating the license with a link to Apache 2.0 documentation
- updating the FF1 introduction with more info on Feistal modes
- Updating the usage code, based on the latest code changes
> Readme update with license link, content & usage update

- CodeOfConduct.md
- Contributions.md
- index.js
- Adding contributions and code of conduct documents - yet to be filled, 
- the files are placeholders 
- updating the index js for testing
> Contributions and code of conduct documents

- Contributions.md
Added the how for creating a PR
Added steps to follow
> Update Contributions.md - steps to follow for PR

- index.js
- updating the sample code to test the module
- removed/updated comments
> Update index.js - updated the example code

- FF-1/Ciphers.js
- cleaning up irrelevant comments
- adding comments on the top of functions to explain the parameters passed into them
> Update Ciphers.js - updating the code comments

- FF-1/Ciphers.js
- FF-1/FF1.js
- FF-1/common-utils/Constants.js
- updating the constants with more static values that were distributed across the library and 
- optimized the imports
> Updating constants and optimizing imports

- FF-1/CryptoUtil.js
- FF-1/FPEncryption.js
- FF-1/common-utils/Constants.js
- updated constants with base64 constants, and 
- added more comments in the cryptoUtil for methods
> updated constants with base64 constants, and adding comments

- FF-1/common-utils/CommonUtils.js
- updating the usage doc for each utility function in the common utils class to make it more readable and easier for the consumer to consume
> Comments & Usage doc update in Common Utils

- FF-1/common-utils/CommonUtils.js
- package.json
- updating the constants in the common utils with the ones in Constants master file, and 
- updating the node version from 10.0.0 to 14.0.0 in package.json
> Common utils constants update plus Node version update in package json

- FF-1/CryptoUtil.js
- adding detailed comments & code documentation to explain the usage of each method/function in CryptoUtil.js
- explaining the use of functions, method parameters and return values
> Code comments and method documentation

- FF-1/CryptoUtil.js
- FF-1/common-utils/CommonUtils.js
- Refactoring cryptoUtil by removing all common methods 
- All the removed methods are added to CommonUtils.js for standardization
> Refactoring CryptoUtil

- Contributions.md
- updating the contributions.md to include standards for a pull request
- adding the requirements for contributors to create a PR as per a standard guideline.
> Update Contributions.md (documentation)

- FF-1/CharMap.js
- FF-1/FPEncryption.js
- updating the code documentation to explain the purpose of char map function, its input and return type, same with wrapper methods in FPEncryption js
> code documentation update charMap and FPEncryption.js (documentation)

- FF-1/CryptoUtil.js
- FF-1/common-utils/CommonUtils.js
- index.js
- adding a fix for radixed string conversion & deradixed int array conversion in common utils by removing a validation check that was causing errors
> validation fix in Common Util (defect-fix)

- FF-1/CryptoUtil.js
- FF-1/common-utils/CommonUtils.js
- reorganizing the common utils and further extracting common functions from cryptoUtil and breaking down functions inside commonUtils for getting updatedCharMap
> CommonUtils Reorganization (code-cleanup-reorg)

- FF-1/common-utils/CommonUtils.js
- updated the char map function code documentation explaining the purpose of the function
> Update Code Docs CommonUtils.js

- FF-1/common-utils/CommonUtils.js
- adding code documentation for common utils num function
> CommonUtils Num Code Documentation

- FF-1/Ciphers.js
- adding code documentation for the Cipher method bitstring that converts a string to bits
> cipher js code documentation for bit string function

- FF-1/Ciphers.js
- FF-1/CryptoUtil.js
- FF-1/common-utils/CommonUtils.js
- cleaning up the code of unnecessary vars in the file, adding additional code documentation for commonUtils
> Code cleanup plus Code documentation

- CodeOfConduct.md
- FF-1/Ciphers.js
- updating the code documentation in Ciphers js to adhere to standard format followed in other parts of the project, 
- added a few pointers in code of conduct document
> Code of conduct and code documentation

- FF-1/common-utils/CommonUtils.js
- adding additional field validations for the common utils functions such as "sanitized inputs", "charArrays" etc
> Field Validations - Common Utils

- CodeOfConduct.md
- FF-1/Ciphers.js
- FF-1/CryptoUtil.js
- FF-1/common-utils/CommonUtils.js
- manually merging develop into main for rebasing
- syncing the changes
> Manual merge from develop to main

- FF-1/Ciphers.js
- FF-1/FF1.js
- FF-1/common-utils/CommonUtils.js
- FF-1/common-utils/Constants.js
- removing unnecessary comments and adding relevant comments in other places such as important global variables and code functionalities
> Code cleanup and documentation

- FF-1/Ciphers.js
- FF-1/FF1.js
- FF-1/common-utils/CommonUtils.js
- FF-1/common-utils/Constants.js
- rebasing the main branch by bringing all the changes accumulated in develop
- syncing main with develop
> Manual merge from develop to main to rebase

- FF-1/common-utils/Constants.js
- adding code comments to constants in constants js file for readability
> Constants code comments

- CODE_OF_CONDUCT.md
- CodeOfConduct.md
- FF-1/CryptoUtil.js
- FF-1/FPEncryption.js
- FF-1/common-utils/Constants.js
- added code documentation to constants and variables, 
- fixed typos and updated the code of conduct document, 
- renamed the contributions and code of conduct document
> Code of Conduct and Code Comments

- CODE_OF_CONDUCT.md
- adding a new section in the Code of Conduct document
- adding the expectations of the repository contributions
- listing out the favorable and unfavorable actions permitted & intolerable respectively in the repo
> Expectations section included in CODE_OF_CONDUCT.md

- CODE_OF_CONDUCT.md
- added a section for unacceptable activities in this repository/project
> Unacceptables section in CODE_OF_CONDUCT.md

- CODE_OF_CONDUCT.md
- updating the consequences of unacceptable behavior in the repository.
> code of conduct update - new sub section addition

- CODE_OF_CONDUCT.md
- code of conduct sub sections for handling grievances and reporting guidelines
> Additional sub-sections for honoring code of conduct

- CODE_OF_CONDUCT.md
> scope in code of conduct

- README.md
- updating the readme with code of conduct reference
- added the sub-section as a point of reference for future contributors
> Code of conduct update in README.md

- FF-1/FF1.js
- index.js
- code comments in FF1, and index.js
> Code comments in FF1 & Index.js

- .gitignore
- adding more extensions and types off files to ignore in .gitignore file
- adding folder types to exclude
> Adding more file extensions and types in .gitignore

- index.js
- updating index.js with copyright & license verbiage as the header
> Adding copyright text

- README.md
- updating the readme document with hyperlinks for code of conduct, contributions and index js files
- making the readme more readable and user-friendly
> Readme update with hyperlinks

- FF-1/CharMap.js
- FF-1/Ciphers.js
- FF-1/CryptoUtil.js
- FF-1/FF1.js
- FF-1/FPEncryption.js
- FF-1/common-utils/CommonUtils.js
- FF-1/common-utils/Constants.js
- index.js
- package.json
- adding Apache License boilerplate on all code files
- updating the package json with emails of contributors 
- adding contributor and primary author details in the code files along with the license boilerplate
> Adding Apache License Copyright boilerplate on all the code files

- .gitignore
- CODE_OF_CONDUCT.md
- FF-1/CharMap.js
- FF-1/Ciphers.js
- FF-1/CryptoUtil.js
- FF-1/FF1.js
- FF-1/FPEncryption.js
- FF-1/common-utils/CommonUtils.js
- FF-1/common-utils/Constants.js
- README.md
- index.js
- package.json
- manual merge to rebase develop with main
- manual merge of all copyright, readme, code of conduct and license changes
> Manually merging develop into main

- Contributions.md
- added sample pull request template for the developer community to refer and use to create PRs in this repo
> Sample Pull request template - Update Contributions.md

- package.json
- updating crypto js library version
- updating the node fpe library version
> Package Json Version Upgrades

- Contributions.md
- Rebasing the develop branch to main branch
- Bringing all the commits from develop to main
- Manual merge
> develop to main merge

- Contributions.md
- added notes about test coverage
- added comments about general contribution guidance
> Adding notes and updates to CONTRIBUTIONS.md

- CODE_OF_CONDUCT.md
- Contributions.md
- bringing all the changes from develop to main branch
- syncing all the changes from all the topic branches to the main
> Merging develop into main to rebase

- FF-1/CryptoUtil.js
- code comments update in CryptoUtil.js
- FF1 string wrapper
> Code comments update in CryptoUtil.js

- FF-1/common-utils/CommonUtils.js
- updating code comments for CommonUtil methods such as modBigInt, convertReadixedString etc
- updating the existing comments to make them more readable
> Code Comments - update CommonUtils.js

- CODE_OF_CONDUCT.md
- updating reference links and section titles
- updating reference links to contributions file and author email
> Reference Links Update in CODE_OF_CONDUCT.md

- FF-1/Ciphers.js
- merging the changes from all PRs to develop
- merging develop into main
> develop to main syncing

- CODE_OF_CONDUCT.md
- README.md
- syncing the branches to bring all up to date changes across the main & develop
> develop to main scheduled sync up

- FF-1/Ciphers.js
- FF-1/CryptoUtil.js
- FF-1/FPEncryption.js
- adding code comments wherever was missing and 
- updating the existing code comments
> updated code comments for util and cipher js

- FF-1/Ciphers.js
- FF-1/CryptoUtil.js
- FF-1/FPEncryption.js
- README.md
- develop to main scheduled sync up
- merging the latest topic branch changes from develop to main
> develop to main rebase

- README.md
- indentation and content update
- comment update for tweak
> Indentation & content update - README.md

- Contributions.md
- adding additional installation instructions 
- removing certain formatting styles for the commit template example
> Changing formatting - Update Contributions.md

- Contributions.md
- README.md
- merging changes from develop to master
- adding the contributions change to master
> develop to master sync up

- README.md
- fixing grammatical issues
- updating the future update pointers
> Updating readme future updates section
